test:
  #  hostport: httpbin.org:80
  #  hostport: localhost:5000
  #  uri: http://${test.hostport}
  uri: http://httpbin.org:80
  #  uri: lb://httpbin

spring:
  jmx:
    enabled: false
  cloud:
    gateway:
      default-filters:
      # - PrefixPath=/httpbin
      # - PrefixPath=/
      - AddResponseHeader=X-Response-Default-Foo, Default-Bar

      routes:
      # =====================================
      # to run server
      # $ wscat --listen 9000
      # to run client
      # $ wscat --connect ws://localhost:8080/echo
      - id: websocket_test
        uri: ws://localhost:9000
        order: 9000
        predicates:
        - Path=/echo
      # =====================================
      - id: token_route
        uri: ${test.uri}
        order: 9999
        predicates:
        - Path=/**
        - Token=CC
        filters:
        - AddResponseHeader=KK05, token_route
        - Time
      - id: default_path_to_httpbin
        uri: ${test.uri}
        order: 10000
        predicates:
        - Path=/**
        filters:
        - AddResponseHeader=KK01, default_path_to_httpbin
        - Time
      - id: kk_route
        uri: 'http://httpbin.org:80'
        order: 9990
        predicates:
        - Path=/kk/**
        filters:
        - StripPrefix=1
        - PrefixPath=/status
        - AddResponseHeader=KK08, kk_route

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG

management.endpoints.web.exposure.include: '*'
